services:
  - name: rasa
    type: web
    env: docker
    buildCommand: ""  # Comando de construcción si es necesario
    startCommand: "rasa run --enable-api --cors '*' --debug"  # Ajustar según tu configuración
    envVars:
      - key: PORT
        value: "5005"
      - key: RENDER_MOUNTS
        value: |
          [
            {
              "type": "volume",
              "name": "rasa-vol",
              "path": "/app",
              "source": "."
            }
          ]
    plan: free
    healthCheckPath: /status

  - name: action-server
    type: web
    env: docker
    buildCommand: ""  # Comando de construcción si es necesario
    startCommand: "rasa run actions --debug"  # Ajustar según tu configuración
    envVars:
      - key: PORT
        value: "5055"
      - key: RENDER_MOUNTS
        value: |
          [
            {
              "type": "volume",
              "name": "actions-vol",
              "path": "/app/actions",
              "source": "./actions"
            },
            {
              "type": "volume",
              "name": "data-vol",
              "path": "/app/data",
              "source": "./data"
            }
          ]
    plan: free
    healthCheckPath: /status
