services:
  - type: web
    name: rasa
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildCommand: ""  # Comando de construcción si es necesario
    startCommand: "rasa run --enable-api --cors '*' --debug"  # Ajustar según tu configuración
    envVars:
      - key: PORT
        value: "5005"
    mounts:
      - type: volume
        name: rasa-vol
        path: /app
        source: .
    plan: free
    healthCheckPath: /status

  - type: web
    name: action-server
    env: docker
    dockerfilePath: ./actions/Dockerfile
    autoDeploy: true
    buildCommand: ""  # Comando de construcción si es necesario
    startCommand: "rasa run actions --debug"  # Ajustar según tu configuración
    envVars:
      - key: PORT
        value: "5055"
    mounts:
      - type: volume
        name: actions-vol
        path: /app/actions
        source: ./actions
      - type: volume
        name: data-vol
        path: /app/data
        source: ./data
    plan: free
    healthCheckPath: /status