services:
  - type: worker
    name: rasa_server
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "5005"
    plan: free

  - type: worker
    name: action_server
    runtime: docker
    dockerfilePath: ./actions/Dockerfile
    envVars:
      - key: PORT
        value: "5055"
    plan: free